language: php

dist: precise

jobs:
  include:
    - php: 7.1
      dist: bionic
    - php: 7.2
      dist: bionic
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic
    - php: 8.0
      dist: bionic
    - php: nightly

matrix:
    allow_failures:
        - nightly

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer update $DEFAULT_COMPOSER_FLAGS $PREFER_LOWEST

before_script:
  - php --version
  - composer --version

script:
  - composer run phpcs
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
